[[main]]
  name = "Blogging"
  identifier = "blogging"
#  pre = '<i class="fas fa-fw fa-chevron-circle-down"></i>'

#
#[[main]]
#  id = "github"
#  parent = "blogging"
# url = "https://github.com/razonyang/hugo-theme-bootstrap"
#  pre = '<i class="fab fa-fw fa-github"></i>'
#